language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script: true
before_install:
- openssl aes-256-cbc -K $encrypted_723e741bc86f_key -iv $encrypted_723e741bc86f_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
after_success:
- ssh root@172.104.111.71 -p 10022 -o StrictHostKeyChecking=no 'cd /var/www/Blog && git
  pull
