# Generated by Django 2.2.5 on 2019-12-04 10:45

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20171226_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_blog',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=markdownx.models.MarkdownxField(default=''),
        ),
    ]
