# Generated by Django 2.2.5 on 2019-12-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20191204_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_bio',
            field=models.BooleanField(default=False),
        ),
    ]
