# Generated by Django 2.2.5 on 2019-12-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20191204_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_todolist',
            field=models.BooleanField(default=False),
        ),
    ]
